### ISSUE TITLE
Ubuntu 16.04 has Boost 1.58, but the required boost::unit_test::data is part of Boost >= 1.59

### ISSUE THREAD

**Issue by marnix** [giomasce/mmpp#3]
The addition of boost::unit_test::data, for xrange (see diff https://github.com/giomasce/mmpp/commit/673f7de68458f9065882898a563dbcea758db337#diff-041c9b3c31d7bf42b4e96a5bf35622dfR11) broke the build on Ubuntu 16.04:

```
g++ -c -m64 -pipe -g -ftemplate-backtrace-limit=0 -Og -std=c++1y -Wall -W -fPIC -DPROJ_DIR="\"/home/marnix/projects/mmpp\"" -DUSE_MICROHTTPD -DUSE_Z3 -I../../mmpp -I. -isystem /usr/include/p11-kit-1 -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o unification.o ../old/unification.cpp
In file included from ../old/unification.cpp:10:0:
../../mmpp/test/test.h:12:61: fatal error: boost/test/data/monomorphic/generators/xrange.hpp: No such file or directory
compilation terminated.
Makefile:614: recipe for target 'unification.o' failed
make: *** [unification.o] Error 1
```

At least my system has packages libboost-test1.58-dev and libboost-test1.58.0 for boost::unit_test.

And boost::unit_test::data was added in 1.59, it looks like.  (I deduce that from the phrase "data driven test cases" under the 'Boost.Test v3' heading in [the Boost 1.59 release notes](https://www.boost.org/users/history/version_1_59_0.html), together with [the 1.59.0 documentation](https://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/tests_organization/test_cases/test_case_generation/datasets_auto_registration.html).)

**Comment by giomasce** [comment]
For the moment `xrange` is not very used, so the easiest thing is just to work around it. I will push a commit soon. Thanks for reporting!

**Comment by giomasce** [comment]
Commit pushed, but I do not have an environment to check. Please reopen if the bug is still there.

**Comment by marnix** [comment]
Thanks for that fast response!  I'm afraid it is not just `xrange`, though: it is _all_ uses of `boost::unit_test::data` and `boost/test/data` that fail with Boost 1.58.

With that additional commit I now see multiple files failing to compile on `test_case.hpp`:
```
g++ -c -m64 -pipe -g -ftemplate-backtrace-limit=0 -Og -std=c++1y -Wall -W -fPIC -DPROJ_DIR="\"/home/marnix/projects/mmpp\"" -DUSE_MICROHTTPD -DUSE_Z3 -I../../mmpp -I. -isystem /usr/include/p11-kit-1 -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o unification.o ../old/unification.cpp
In file included from ../old/unification.cpp:10:0:
../../mmpp/test/test.h:12:41: fatal error: boost/test/data/test_case.hpp: No such file or directory
compilation terminated.
Makefile:614: recipe for target 'unification.o' failed
make: *** [unification.o] Error 1
```

So to support Boost 1.58 you would probably have to changes all of the following :-( :
```
$ grep -E -R 'unit_test::data|boost/test/data' ..
../test/test_minor.cpp:BOOST_DATA_TEST_CASE(test_compressed_decoder_encoder, boost::unit_test::data::make(test_enc) ^ boost::unit_test::data::make(test_dec), enc, dec) {
../test/test_parsing.cpp:BOOST_DATA_TEST_CASE(test_unification, boost::unit_test::data::make(unification_data)) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_type_proving, boost::unit_test::data::make(type_proving_data)) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_wff_type_prover, boost::unit_test::data::make(wff_data), trivially_true, trivially_false, actually_true, wff) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_wff_truth_prover, boost::unit_test::data::make(wff_data), trivially_true, trivially_false, actually_true, wff) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_wff_falsity_prover, boost::unit_test::data::make(wff_data), trivially_true, trivially_false, actually_true, wff) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_wff_adv_truth_prover, boost::unit_test::data::make(wff_data), trivially_true, trivially_false, actually_true, wff) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_wff_minisat_prover, boost::unit_test::data::make(wff_data), trivially_true, trivially_false, actually_true, wff) {
../test/test_wff.cpp:BOOST_DATA_TEST_CASE(test_wff_from_pt, boost::unit_test::data::make(wff_from_pt_data)) {
../test/test.h:#include <boost/test/data/test_case.hpp>
../test/test.h:#include <boost/test/data/monomorphic.hpp>
../provers/z3prover.cpp:BOOST_DATA_TEST_CASE(test_wff_minisat_prover, boost::unit_test::data::make(range3), i) {
```

Removing all of those is probably going in the wrong direction...

----

Suggestion: What if compiling/running the tests could be optional?

**Comment by marnix** [comment]
(Note that I cannot reopen this issue, by GitHub's design, see https://stackoverflow.com/a/21333938/223837 and https://github.com/isaacs/github/issues/583.)

**Comment by giomasce** [comment]
Oh yes, you are right. It is probably better to disable the tests, which should not be a big burden, since I have to do that for Windows anyway.

**Comment by giomasce** [comment]
I had another try. Now you can disable all tests by changing `DISABLE_TESTS` to `true` in `mmpp.pro`. Can you confirm it works? Thanks again.

**Comment by marnix** [comment]
I have good and bad news. The good news is that this issue has now been resolved: compilation on Ubuntu 16.04 / xenial with Boost 1.58 no longer fails with `DISABLE_TESTS` set to `true`.

The bad news is that compilation now fails elsewhere for me, on something that seems related to C++11 vs C++14.  I'm still looking into that, and will log an issue probably soon.
