### ISSUE TITLE
‘ifstream’ in namespace ‘boost::filesystem’ does not name a type

### ISSUE THREAD

**Issue by jkingdon** [giomasce/mmpp#2]
When I build on Ubuntu 16.04 using the instructions in the README, I get:

```
../mm/tokenizer.h:35:24: error: ‘ifstream’ in namespace ‘boost::filesystem’ does not name a type
```

The version of boost from `dpkg -l | grep boost-all-dev` is `1.58.0.1ubuntu1` .

**Comment by giomasce** [comment]
Boost 1.58 should be ok according to the docs. The problem is probably caused by some missing includes. Please try again with the last commit and reopen if it does not fix.

**Comment by jkingdon** [comment]
Pulling the latest fixes the problem
